spring:
  datasource:
    url: jdbc:mysql://chatnshop-dev.cbe8gc4kyovu.us-east-2.rds.amazonaws.com:3306/ecommerce_orders
    username: admin
    password: jaqart_56923
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  cache:
    type: simple
#    type: redis

#  data:
#    redis:
#      host: localhost
#      port: 6379

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE